kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
  annotations:
    configsync.gke.io/cluster-name-selector: gke-dev-1
spec:
  podSelector:
    matchLabels:
      app: web
  ingress: []
